FROM node:16

# temp fix for CLI change is to install explicit version
RUN npm install --global @superfaceai/cli@1.0.1 @superfaceai/one-service

RUN mkdir /app
WORKDIR /app

ADD superface .

EXPOSE 8000
ENTRYPOINT ["oneservice", "--host", "0.0.0.0"]
